* emacs-organizer

Some code should be executing before tangling and evaluating this file.
So, look at init.el

** layout
I use colemak keyboard layout see layout.org file -- [[./layout.org][link]]

** Dependensies

This emacs configuration depends on:
- ability of emacs to use gui features to render formulas
- texlive or miktex for describing formulas
- perl as a dependency for latexmk
- clangd for C and C++ programming
- gnu coreutils for dired on OpenBSD

** general emacs
*** Add 4 main package archives
#+begin_src elisp
(require 'package)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/") t)
(package-initialize)
#+end_src

#+RESULTS:


*** Set priorites for package-archives
#+begin_src elisp
(setq package-archive-priorities
  '(("gnu" . 40)
    ("nongnu" . 30)
    ("melpa-stable" . 20)
    ("melpa" . 10)))
#+end_src

#+RESULTS:
: ((gnu . 40) (nongnu . 30) (melpa-stable . 20) (melpa . 10))


*** window management
**** transpose frame
If frame is devided by top and bottom, change it to left and right.
Transpose operation like with matrices and tables.
#+BEGIN_SRC elisp
(use-package transpose-frame)
#+END_SRC

#+RESULTS:
: t

**** enable tab-bar-mode
#+begin_src elisp
  (setq tab-bar-mode t)
#+end_src

#+RESULTS:
: t

*** autocomplete
Press C-M-i to activate emacs autocomplete.

Frankly speaking, I copy this snippet from the official vertico docs:

https://github.com/minad/vertico?tab=readme-ov-file#completion-at-point-and-completion-in-region

This configuration give my ability to perform fuzzy search.
Like with dmenu, rofi or fzf, but in emacs.

#+BEGIN_SRC elisp
(use-package vertico
  :init (vertico-mode)
   (setq completion-in-region-function
	    (lambda (&rest args)
	      (apply (if vertico-mode
			 #'consult-completion-in-region
		       #'completion--in-region)
		     args))))

 (use-package consult)

 (use-package consult-eglot)
#+END_SRC



*** Force UTF-8 and LF line endings

This should be executed before loading this file,
so this forms also present in init.el.
#+BEGIN_SRC elisp
(defvar *fs-encoding* 'utf-8)
(prefer-coding-system 'utf-8-unix)
#+END_SRC


** use cases of my emacs config
I structured my config by use cases I apply emacs in.

*** study organizer

**** Notes, personal wiki, z-word — howm

I use handy own wiki mode, and I use it by a lot.
I use howm with org mode, to do this I
1. changed =howm-view-title-header= to org-mode title
2. changed =howm-file-name-format= to end with org file name extension.


#+begin_src elisp
(use-package howm
  :init (setq howm-view-title-header "*")
  (setq howm-file-name-format "%Y/%m/%Y-%m-%d-%H%M%S.org")
  :pin "melpa")
  ;; :custom
  ;; (howm-view-use-grep 't))
#+end_src

#+RESULTS:

**** Problem with howm on windows
I commented =howm-vies-use-grep= variable, because on windows,
with installed grep from scoop,
is is somehow made searching slower.

**** Various org-todo-keywords
#+begin_src elisp
  (setq org-todo-keywords
      '((sequence "TODO" "|" "DONE" "FAIL" "NGMI" )))
#+end_src

#+RESULTS:
| sequence | TODO |   |   | DONE | FAIL | NGMI |

**** pomodoro timer inside notes
I use org-pomodoro.

#+BEGIN_SRC elisp
(use-package org-pomodoro)
#+END_SRC

#+RESULTS:

***** Work arounds
Use C locale for time on windows

#+begin_src elisp
(when (eq system-type 'windows-nt)
(setq system-time-locale "C"))
#+end_src

#+RESULTS:
: C




***** TODO Create ffplay-sound to play sound using cross-platform ffplay

**** flashcards inside notes: org-fc

***** Integration with howm
****** Constants with regexp
#+BEGIN_SRC elisp
  (defconst my-howm-subsubdir-regexp
  (rx (seq "howm/" (= 4 num ) "/" (= 2 num)))
  "Regexp that matches second level of subdirectories in howm,
   like  ~/homw/2024/01/, but with ltximg")



(defconst my-howm-excluded-subdirs-regexp
  (rx (or ".git" ".elfeed" "ltximg"))
  "Regexp that matches howm subdirs that I don't need
   like .git .elfeed and ltximg, basically like .gitignore,
   but i don't want to rely on them")

#+END_SRC

#+RESULTS:
: my-howm-excluded-subdirs-regexp

****** Exlude files from howm subsubdirs:
#+BEGIN_SRC elisp
  (defun my-howm-subsubdir-exclude (dir)
  (if (string-match-p my-howm-subsubdir-regexp dir)
      (unless
	  (string-match-p my-howm-excluded-subdirs-regexp dir) dir)
    nil))
#+END_SRC

#+RESULTS:
: my-howm-subsubdir-exclude

****** Return filtered list of subsubdirs of howm:
#+BEGIN_SRC elisp
  (defun my-howm-subsubdirs ()
  (thread-last
    (directory-files-recursively
     howm-directory directory-files-no-dot-files-regexp t)
    (seq-filter #'file-directory-p)
    (seq-filter #'my-howm-subsubdir-exclude)))
#+END_SRC

#+RESULTS:
: my-howm-subsubdirs


***** org-fc use-package
#+BEGIN_SRC elisp
(use-package hydra)

(use-package org-fc
  :load-path ("~/.emacs.d/site-lisp/org-fc/")
  :custom
  (org-fc-review-history-file "~/howm/.org-fc-reviews.tsv")
  (org-fc-directories (my-howm-subsubdirs))
  (org-fc-mixed-line-endings t)
  :config
  (require 'org-fc-hydra)
  :after howm)
  
#+END_SRC

#+RESULTS:
: t
***** DONE Make org-fc usable on Windows
Solve [[https://todo.sr.ht/~l3kn/org-fc/43][this]] issue.


****** DONE Try to use busybox from scoop
Busybox from [[https://scoop.sh][scoop]] has xargs, find and I already installed gawk.

****** org-fc-awk--find on windows
Done without =shell-quote-argument= function,
because this function by escaping files made them impossible to find.
For instance it escapes =c:/= as =c\:/= and it breaks ability to find files.

#+begin_src elisp
    (when (eq system-type 'windows-nt)
      (defun org-fc-awk--find (paths)
  	    (format
  "C:\\Users\\artsi0m\\scoop\\shims\\find.exe -L %s -type f -name \"*.org\" -not -name \".*\"  -print0" ;;
  	   (mapconcat  (lambda (path)
(shell-quote-argument (expand-file-name path)))
  		       paths " ")))) 
#+end_src

#+RESULTS:
: org-fc-awk--find

****** org-fc-awk--xargs on windows
#+begin_src elisp
  (when (eq system-type 'windows-nt)
    (defun org-fc-awk--xargs (command)
    (concat "C:\\Users\\artsi0m\\scoop\\shims\\xargs -0 "  command)))
#+end_src

#+RESULTS:
: org-fc-awk--xargs

****** Set path for gawk on windows
#+BEGIN_SRC elisp
(when (eq system-type 'windows-nt)
 (setq org-fc-review-history-file "c:/Users/artsi0m/howm/.org-fc-reviews.tsv"))
#+END_SRC

****** Error that I get sometimes with this setup
#+begin_src
(:path "-" :cards (
  )  :title nil)
#+end_src

**** flashcards inside notes: org-drill
I am trying to switch to org-fc by now.

#+BEGIN_SRC elisp
(use-package org-drill
  :after howm)
#+END_SRC



*****  Function for discovering org-drill cards in howm
#+BEGIN_SRC elisp
(defun my-org-drill-file-names-in-howm ()
  "Return list of absolute filenames of org-drill files in howm"
  (delete-dups
   (mapcar #'car (howm-grep "\:drill\:"
			    (howm-files-in-directory howm-directory)))))
#+END_SRC

***** Command for creating new org-drill cards.

I want to create less of them, actually.
But by now I want some kind of separtion,
therefor there is dedicated dir in howm.

#+BEGIN_SRC elisp
  (defun my-org-drill-create ()
    (interactive)
    (let ((filename   (format "~/howm/org.drill.cards/%s.org"
				      (format-time-string "%F-%H%M%S"))))
	    (make-empty-file filename)
	    (switch-to-buffer filename)
	    (set-visited-file-name filename)
	    (org-mode)
	    (howm-mode)
	    (org-insert-heading)))

#+END_SRC

#+RESULTS:
: my-org-drill-create


**** DONE Try to use org-gcal
o
**** calendar interconnected with notes: calfw
Calfw use dates from holidays.el by default,
but there is packages that adds org and howm dates support.
There is also ability to get schedule from iis.bsuir.by in iCalendar format.

#+BEGIN_SRC elisp
(use-package calfw-org :after calfw)
(use-package calfw-howm :after calfw)
#+END_SRC

***** use-package and calendar command
#+BEGIN_SRC elisp
  (use-package calfw
  :config
  (require 'calfw-org)
  (require 'calfw-howm)
  
  (defun my-open-calendar ()
    (interactive)
    (setq org-agenda-files (my-org-agenda-file-names-in-howm))
    (cfw:open-calendar-buffer
     :contents-sources
     (list
      (cfw:org-create-source)
      (cfw:howm-create-source))))
  
  :after howm)
#+END_SRC

#+RESULTS:

***** Draw calendar in howm (inline)
Append function into howm allowed functions,
that howm would execute after start.
#+BEGIN_SRC elisp
(setq howm-menu-allow
	    (append '(cfw:howm-schedule-inline) howm-menu-allow))
#+END_SRC

**** Timeblocking with org-timeblock
By now [2024-02-18] org-timeblock is broken on my side.
However I may use =org-timeblock-list=

#+BEGIN_SRC elisp
    (use-package org-timeblock
      :load-path "~/.emacs.d/site-lisp/org-timeblock")
#+END_SRC

#+RESULTS:

***** DONE Fix org-timeblock
At first switch to commit when it worked.

**** Coursework and various docs
I write my coursework in xelatex.
#+BEGIN_SRC elisp
(setq-default TeX-engine 'xetex)
#+END_SRC

#+RESULTS:
: xetex



*** programming
**** language server client
#+BEGIN_SRC elisp
(use-package eglot)
#+END_SRC

****  python venv support
#+BEGIN_SRC elisp
(use-package pyvenv)
#+END_SRC

**** matlab course from university
https://github.com/emacsmirror/matlab-mode

***** DONE Try to use matlabShell for MS-Windows
https://www.emacswiki.org/emacs/MatlabMode#h5o-3
#+begin_src elisp
  (setq matlab-shell-command
	"c:/Users/artsi0m/matlabShell/matlabshell.cmd")
  (setq matlab-shell-command-switches '())
  (setq matlab-shell-echoes nil)
#+end_src

#+RESULTS:

***** NGMI Try to use matlab from WSL

**** Use sbcl as lisp interpreter
#+begin_src elisp
  (setq inferior-lisp-program "sbcl")
#+end_src

#+RESULTS:
: sbcl

*** file manager
I use build in dired for now.

**** Copy, move, rename files across panes
#+BEGIN_SRC elisp
  (setq dired-dwim-target t)
#+END_SRC

#+RESULTS:
: t

**** Work-arounds

***** OpenBSD
Use ls from GNU coreutils on OpenBSD
#+BEGIN_SRC elisp
  (when (eq system-type 'berkeley-unix)
  (setq insert-directory-program "gls")) 
#+END_SRC



*** rss reader 
Elfeed in my config is interconneted with howm.

**** elfeed use-package:
#+BEGIN_SRC elisp
  (use-package elfeed
  :ensure t
  :config
  (setq elfeed-db-directory "~/howm/.elfeed")
    (setq elfeed-curl-program-name "curl"))
  
  (use-package elfeed-protocol) 
#+END_SRC

**** elfeed-org use-package
#+BEGIN_SRC elisp
(use-package elfeed-org
  :ensure t
  :config
  (elfeed-org)
  :after howm)
#+END_SRC

**** functions for interconnecting with howm
#+BEGIN_SRC elisp
(defun my-elfeed-file-names-in-howm ()
  "Return list of absolute filenames of org-elfeed files in howm"
  (delete-dups
   (mapcar #'car (howm-grep "\:elfeed\:"
		      (howm-files-in-directory howm-directory)))))
  
#+END_SRC

**** advices for executing functions
#+BEGIN_SRC elisp
(define-advice elfeed (:before (&rest _args))
  (setq rmh-elfeed-org-files (my-elfeed-file-names-in-howm)))


(define-advice elfeed-update (:before (&rest _args))
  (setq rmh-elfeed-org-files (my-elfeed-file-names-in-howm)))
#+END_SRC

*** email client

I use gnus with =nnimap= source.

This is not the best choice, because with [[https://cr.yp.to/proto/maildir.html][maildir]] it would be indexed fast.
Other pluses of maildir:
- You store your mail locally which means you distrust ifrastracture of mail provider.
- You store your mail locally which means you don't need internet connection.
- You can configure other program for fetching and indexing.

Minuses of maildir:
- You can't use it on Windows, not enough programms to fetch and index.
  
**** Configured with custom
I configured my gnus setup enterily with custom,
see =custom-set-variables= in init.el

