* Multilingua layouts and emacs IME
I use colemak keyboard layout for more than five years.

I started using it when I needed [[https://colemak.com/Multilingual][multilungual]] keyboard layout.
It happened when I was learning German in Goethe Institut.
Unfortunately, by now I completely forget what I was learning,
but now I have this [[https://colemak.com/Ergonomic][ergonomic]] layout.
I can type in this layout without looking at keyboard,
and I can't do this with qwerty.

As for October 2024 I use Russian (Belarus) layout which is also an
multilingual layout that contain Cyrillic letters with some of them
used in Belarusian language and accessible with Alt-GR. I also started
using reverse-im package.

** =setxkbmap -query= output:
#+begin_src
rules:      evdev
model:      microsoftpro
layout:     us,by
variant:    colemak,ru
options:    grp:win_space_toggle
#+end_src



** enabling colemak layout
*** OpenBSD kernel wsconsole
OpenBSD 6.6 was nice release, where it was introduced:

#+BEGIN_SRC shell :eval no 
kbd us.colemak
#+END_SRC

*** X11
With russian layout
#+BEGIN_SRC shell :eval no 
  setxkbmap us, by -variant colemak,ru
#+END_SRC

**** Windows

https://colemak.com/Windows

**** OpenSUSE-Tumbleweed
#+BEGIN_SRC shell :eval no
localectl set-keymap us-colemak 
#+END_SRC
